### ISSUE TITLE
How get better error message ?

### ISSUE THREAD

**Issue by afaucogney** [bitrise-steplib/steps-danger#5]
Hello,

 Danger is started, and push some comment on Gitlab (selfhosted) but it failed.

```
Checking dependencies
Bundler...
Bundler installed
Installing dependencies from your gem file
$ bundle "install"
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/...........
Fetching public_suffix 3.1.1
Installing public_suffix 3.1.1
Using addressable 2.6.0
Fetching ansi 1.5.0
Installing ansi 1.5.0
Fetching ast 2.4.0
Installing ast 2.4.0
Using bundler 1.17.3
Fetching claide 1.0.2
Installing claide 1.0.2
Using colored2 3.1.2
Fetching cork 0.3.0
Installing cork 0.3.0
Fetching nap 1.1.0
Installing nap 1.1.0
Fetching open4 1.3.4
Installing open4 1.3.4
Fetching claide-plugins 0.9.2
Installing claide-plugins 0.9.2
Fetching multipart-post 2.1.1
Installing multipart-post 2.1.1
Using faraday 0.15.4
Fetching faraday-http-cache 2.0.0
Installing faraday-http-cache 2.0.0
Fetching git 1.5.0
Installing git 1.5.0
Fetching kramdown 2.1.0
Installing kramdown 2.1.0
Fetching kramdown-parser-gfm 1.1.0
Installing kramdown-parser-gfm 1.1.0
Fetching no_proxy_fix 0.1.2
Installing no_proxy_fix 0.1.2
Fetching sawyer 0.8.2
Installing sawyer 0.8.2
Fetching octokit 4.14.0
Installing octokit 4.14.0
Using unicode-display_width 1.6.0
Using terminal-table 1.8.0
Fetching danger 6.0.9
Installing danger 6.0.9
Fetching danger-plugin-api 1.0.0
Installing danger-plugin-api 1.0.0
Fetching ruby-ll 2.1.2
Installing ruby-ll 2.1.2 with native extensions
Fetching oga 2.15
Installing oga 2.15 with native extensions
Fetching danger-android_lint 0.0.7
Installing danger-android_lint 0.0.7
Fetching danger-apkstats 0.2.0
Installing danger-apkstats 0.2.0
Using mime-types-data 3.2019.0331
Using mime-types 3.2.2
Using multi_xml 0.6.0
Fetching httparty 0.17.0
Installing httparty 0.17.0
Fetching gitlab 4.11.0
Installing gitlab 4.11.0
Fetching danger-gitlab 7.0.0
Installing danger-gitlab 7.0.0
Fetching ox 2.11.0
Installing ox 2.11.0 with native extensions
Fetching danger-junit 1.0.0
Installing danger-junit 1.0.0
Fetching danger-kotlin_detekt 0.0.3
Installing danger-kotlin_detekt 0.0.3
Bundle complete! 6 Gemfile dependencies, 37 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from httparty:
When you HTTParty, you must party hard!
Running danger
$ bundle "exec" "danger"
bundler: failed to load command: danger (/usr/local/bin/danger)
Net::OpenTimeout: execution expired
  /usr/local/lib/ruby/2.5.0/net/http.rb:937:in `initialize'
  /usr/local/lib/ruby/2.5.0/net/http.rb:937:in `open'
  /usr/local/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
  /usr/local/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
  /usr/local/lib/ruby/2.5.0/net/http.rb:935:in `connect'
  /usr/local/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  /usr/local/lib/ruby/2.5.0/net/http.rb:909:in `start'
  /usr/local/lib/ruby/2.5.0/net/http.rb:1455:in `request'
  /usr/local/lib/ruby/gems/2.5.0/gems/httparty-0.17.0/lib/httparty/request.rb:145:in `perform'
  /usr/local/lib/ruby/gems/2.5.0/gems/httparty-0.17.0/lib/httparty.rb:593:in `perform_request'
  /usr/local/lib/ruby/gems/2.5.0/gems/httparty-0.17.0/lib/httparty.rb:523:in `post'
  /usr/local/lib/ruby/gems/2.5.0/gems/gitlab-4.11.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
  /usr/local/lib/ruby/gems/2.5.0/gems/gitlab-4.11.0/lib/gitlab/client/merge_requests.rb:235:in `create_merge_request_discussion'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-6.0.9/lib/danger/request_sources/gitlab.rb:433:in `block in submit_inline_comments_for_kind!'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-6.0.9/lib/danger/request_sources/gitlab.rb:387:in `reject'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-6.0.9/lib/danger/request_sources/gitlab.rb:387:in `submit_inline_comments_for_kind!'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-6.0.9/lib/danger/request_sources/gitlab.rb:348:in `submit_inline_comments!'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-6.0.9/lib/danger/request_sources/gitlab.rb:200:in `update_pull_request_with_inline_comments!'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-6.0.9/lib/danger/request_sources/gitlab.rb:165:in `update_pull_request!'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-6.0.9/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-6.0.9/lib/danger/danger_core/dangerfile.rb:278:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-6.0.9/lib/danger/danger_core/executor.rb:29:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-6.0.9/lib/danger/commands/runner.rb:72:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/danger-6.0.9/bin/danger:5:in `<top (required)>'
  /usr/local/bin/danger:23:in `load'
  /usr/local/bin/danger:23:in `<top (required)>'
Failed to run bundle exec danger, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | danger (exit code: 1)                                         | 2.2 min  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-danger/issues        |
| Source: https://github.com/bitrise-steplib/steps-danger                      |
+---+---------------------------------------------------------------+----------+
```

Is there any way to get more info with that step ?

**Comment by bitce** [comment]
Hi @afaucogney, that's a fair question. Could you share the build URL for this one so we can check out the complete logs?

**Comment by afaucogney** [comment]
I'm still getting some issues about this:
```
$ bundle "exec" "danger" "--fail-on-errors=false"
/usr/local/lib/ruby/gems/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/local/lib/ruby/gems/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/local/lib/ruby/gems/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/local/lib/ruby/gems/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/local/lib/ruby/gems/2.7.0/gems/faraday-0.15.4/lib/faraday/options.rb:166: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/local/lib/ruby/gems/2.7.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:55: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
/usr/local/lib/ruby/gems/2.7.0/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: warning: `_1' is reserved for numbered parameter; consider another name
/usr/local/lib/ruby/gems/2.7.0/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: warning: `_2' is reserved for numbered parameter; consider another name
/usr/local/lib/ruby/gems/2.7.0/gems/mime-types-3.2.2/lib/mime/types/logger.rb:30: warning: `_3' is reserved for numbered parameter; consider another name
/usr/local/lib/ruby/gems/2.7.0/gems/gitlab-4.11.0/lib/gitlab/client.rb:74: warning: URI.escape is obsolete
/usr/local/lib/ruby/gems/2.7.0/gems/gitlab-4.11.0/lib/gitlab/client.rb:74: warning: URI.escape is obsolete
/usr/local/lib/ruby/gems/2.7.0/gems/danger-6.0.9/lib/danger/request_sources/gitlab.rb:200: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/lib/ruby/gems/2.7.0/gems/danger-6.0.9/lib/danger/request_sources/gitlab.rb:337: warning: The called method `submit_inline_comments!' is defined here
/usr/local/lib/ruby/gems/2.7.0/gems/danger-6.0.9/lib/danger/request_sources/gitlab.rb:218: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/lib/ruby/gems/2.7.0/gems/danger-6.0.9/lib/danger/helpers/comments_helper.rb:94: warning: The called method `generate_comment' is defined here
/usr/local/lib/ruby/gems/2.7.0/gems/gitlab-4.11.0/lib/gitlab/client.rb:74: warning: URI.escape is obsolete
bundler: failed to load command: danger (/usr/local/bin/danger)
Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>
  /usr/local/lib/ruby/2.7.0/net/protocol.rb:217:in `rbuf_fill'
  /usr/local/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
  /usr/local/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
  /usr/local/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
  /usr/local/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
  /usr/local/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
  /usr/local/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
  /usr/local/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
  /usr/local/lib/ruby/2.7.0/net/http.rb:1492:in `request'
  /usr/local/lib/ruby/2.7.0/net/http.rb:1485:in `block in request'
  /usr/local/lib/ruby/2.7.0/net/http.rb:933:in `start'
  /usr/local/lib/ruby/2.7.0/net/http.rb:1483:in `request'
  /usr/local/lib/ruby/gems/2.7.0/gems/httparty-0.17.0/lib/httparty/request.rb:145:in `perform'
  /usr/local/lib/ruby/gems/2.7.0/gems/httparty-0.17.0/lib/httparty.rb:593:in `perform_request'
  /usr/local/lib/ruby/gems/2.7.0/gems/httparty-0.17.0/lib/httparty.rb:523:in `post'
  /usr/local/lib/ruby/gems/2.7.0/gems/gitlab-4.11.0/lib/gitlab/request.rb:46:in `block (2 levels) in <class:Request>'
  /usr/local/lib/ruby/gems/2.7.0/gems/gitlab-4.11.0/lib/gitlab/client/notes.rb:161:in `create_merge_request_note'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-6.0.9/lib/danger/request_sources/gitlab.rb:226:in `update_pull_request_with_inline_comments!'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-6.0.9/lib/danger/request_sources/gitlab.rb:165:in `update_pull_request!'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-6.0.9/lib/danger/danger_core/dangerfile.rb:247:in `post_results'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-6.0.9/lib/danger/danger_core/dangerfile.rb:278:in `run'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-6.0.9/lib/danger/danger_core/executor.rb:29:in `run'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-6.0.9/lib/danger/commands/runner.rb:72:in `run'
  /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
  /usr/local/lib/ruby/gems/2.7.0/gems/danger-6.0.9/bin/danger:5:in `<top (required)>'
  /usr/local/bin/danger:23:in `load'
  /usr/local/bin/danger:23:in `<top (required)>'
Failed to run bundle exec danger, error: exit status 1
```
@bitce Could we work on that ?

**Comment by istx25** [comment]
Hi @afaucogney,

Can you please share a link to a build and enable support access in project settings?

**Comment by afaucogney** [comment]
https://app.bitrise.io/build/bc8c72da97585911#?tab=log

I did a full manual script that limit issues count of androidLint and Detekt to 50 each, but I still get the timeout issue !

I just eneabled the support ! Keep me in touch @non-binary
